name: file_share
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  cloud_firestore: ^3.4.5
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  qr_flutter: ^4.0.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
